### PR TITLE
Try 2.... sending remote to leader.

### PR DESCRIPTION
**Pull request by Tuxhedoh**

### CODE REVIEW

**Comment by jamesperrin** [comment]
Dean, your files are still not matching.

Your PR is stating the master stylesheet is titled **style-master.css**, but it's actually titled **styles-master.css**.

Example:
Incorrect:
<link rel="stylesheet" href="public/stylesheets/style-master.css">

Correct:
<link rel="stylesheet" href="public/stylesheets/styles-master.css">

**Comment by Tuxhedoh** [comment]
I'm really unsure how to handle that.  I have followed all the advice given.

**Comment by Tuxhedoh** [comment]
When I look at the files here - https://github.com/Tuxhedoh/Udacity-Yearbook-Project/tree/master/public/stylesheets it shows styles-master.css

**Comment by jamesperrin** [comment]
Yes, the file is physically in your repository.

**However...**

In your repo: https://github.com/Tuxhedoh/Udacity-Yearbook-Project
If you look at files **about.html**, **index.html**, **base.html** and **yearbook.html** on line 40, it's incorrect.

**It should be:**
```html
<link rel="stylesheet" href="public/stylesheets/styles-master.css">
```
**But, you have:**
```html
<link rel="stylesheet" href="public/stylesheets/style-master.css">
```

If you look at files **resources.html** on line 40, it's incorrect.

**It should be:**
```html
<link rel="stylesheet" href="public/stylesheets/styles-master.css">
```
**But, you have:**
```html
<link rel="stylesheet" href="public/stylesheets/style.css">
```

**Also...**

You have old versions of these files.

1. public/stylesheets/styles-master.css
1. public/stylesheets/rotating-card.css
1. public/stylesheets/index.css

**Comment by Tuxhedoh** [comment]
I'm driving right now, will get back to you as soon as I can!
Voice text for Inbox! www.drivemo.de/ib

**Comment by jamesperrin** [comment]
I'll have to resolve the issues offline. I'll clone your repo, make the corrections, then do a push.

**Comment by Tuxhedoh** [comment]
Sorry for the hassle. :(

**Comment by jamesperrin** [comment]
Don't worry about. This is a learn experience for everyone. I'm getting better at handling and resolving merge conflicts and Github management..

**Pull request closed without merging**
